import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import NextAuthSessionProvider from "./provider";
import { Toaster } from "@/components/ui/sonner";
import Footer from "./_components/Footer";

const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Go Home Service",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <NextAuthSessionProvider>
          <div className="flex-1 mx-6 md:mx-16">
            <Header />
            <Toaster />
            {children}
          </div>
          <Footer />
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
